package api

import (
	"bytes"
	"encoding/json"
	"strings"
	"testing"

	"codeberg.org/xchangeee/syslet/internal/systemd"
	gounit "github.com/coreos/go-systemd/v22/unit"
	"github.com/spf13/afero"
)

func TestContainerSpec_GetMethods(t *testing.T) {
	spec := &ContainerSpec{
		Name: "webapp",
		Unit: map[string]map[string]UnitValue{
			"Container": {"Image": UV("nginx:latest")},
		},
	}

	if spec.GetName() != "webapp" {
		t.Errorf("expected name 'webapp', got %q", spec.GetName())
	}
	if spec.GetType() != SpecTypeContainer {
		t.Errorf("expected type %q, got %q", SpecTypeContainer, spec.GetType())
	}
	if spec.FullUnitName() != "webapp.container" {
		t.Errorf("expected 'webapp.container', got %q", spec.FullUnitName())
	}
}

func TestContainerSpec_Render_BasicContainer(t *testing.T) {
	spec := &ContainerSpec{
		Name: "webapp",
		Unit: map[string]map[string]UnitValue{
			"Container": {"Image": UV("nginx:latest")},
		},
		DesiredState: "running",
	}

	rendered, err := spec.Render("/etc/containers/config")
	if err != nil {
		t.Fatalf("Render failed: %v", err)
	}

	// Verify ContainerName is set
	hasContainerName := false
	for _, opt := range rendered.UnitOptions {
		if opt.Section == "Container" && opt.Name == "ContainerName" && opt.Value == "webapp" {
			hasContainerName = true
		}
	}
	if !hasContainerName {
		t.Error("expected ContainerName=webapp to be set")
	}

	// Verify Install section is added for running state
	hasInstall := false
	for _, opt := range rendered.UnitOptions {
		if opt.Section == "Install" && opt.Name == "WantedBy" {
			hasInstall = true
		}
	}
	if !hasInstall {
		t.Error("expected Install section for running container")
	}
}

func TestContainerSpec_Render_DesiredStateStopped(t *testing.T) {
	spec := &ContainerSpec{
		Name: "webapp",
		Unit: map[string]map[string]UnitValue{
			"Container": {"Image": UV("nginx:latest")},
		},
		DesiredState: "stopped",
	}

	rendered, err := spec.Render("/etc/containers/config")
	if err != nil {
		t.Fatalf("Render failed: %v", err)
	}

	// Verify Install section is NOT added for stopped state
	for _, opt := range rendered.UnitOptions {
		if opt.Section == "Install" {
			t.Error("expected no Install section for stopped container")
		}
	}
}

func TestContainerSpec_Render_WithConfigs(t *testing.T) {
	spec := &ContainerSpec{
		Name: "webapp",
		Unit: map[string]map[string]UnitValue{
			"Container": {"Image": UV("nginx:latest")},
		},
		Configs: []ConfigEntry{
			{
				Content:          "config content",
				TargetVolumePath: "/etc/nginx/nginx.conf",
			},
			{
				Content:          "another config",
				TargetVolumePath: "/etc/app/config.yaml",
			},
		},
	}

	rendered, err := spec.Render("/etc/containers/config")
	if err != nil {
		t.Fatalf("Render failed: %v", err)
	}

	// Verify config bind mounts were added
	volumeCount := 0
	for _, opt := range rendered.UnitOptions {
		if opt.Section == "Container" && opt.Name == "Volume" {
			volumeCount++
			// Verify mount is read-only
			if !strings.Contains(opt.Value, ":ro") {
				t.Errorf("expected volume mount to be read-only, got %q", opt.Value)
			}
		}
	}
	if volumeCount != 2 {
		t.Errorf("expected 2 config volume mounts, got %d", volumeCount)
	}
}

func TestContainerSpec_Render_ContainerNameNotOverridden(t *testing.T) {
	spec := &ContainerSpec{
		Name: "webapp",
		Unit: map[string]map[string]UnitValue{
			"Container": {
				"Image":         UV("nginx:latest"),
				"ContainerName": UV("custom-name"), // User-specified name
			},
		},
	}

	rendered, err := spec.Render("/etc/containers/config")
	if err != nil {
		t.Fatalf("Render failed: %v", err)
	}

	// Verify user-specified ContainerName is preserved
	containerNameCount := 0
	for _, opt := range rendered.UnitOptions {
		if opt.Section == "Container" && opt.Name == "ContainerName" {
			containerNameCount++
			if opt.Value != "custom-name" {
				t.Errorf("expected custom-name, got %q", opt.Value)
			}
		}
	}
	if containerNameCount != 1 {
		t.Errorf("expected exactly 1 ContainerName, got %d", containerNameCount)
	}
}

func TestContainerSpec_Render_AutoGeneratedDescription(t *testing.T) {
	spec := &ContainerSpec{
		Name: "webapp",
		Unit: map[string]map[string]UnitValue{
			"Container": {"Image": UV("nginx:latest")},
		},
	}

	rendered, err := spec.Render("/etc/containers/config")
	if err != nil {
		t.Fatalf("Render failed: %v", err)
	}

	// Verify auto-generated Description is set
	hasDescription := false
	for _, opt := range rendered.UnitOptions {
		if opt.Section == "Unit" && opt.Name == "Description" && opt.Value == "webapp container" {
			hasDescription = true
		}
	}
	if !hasDescription {
		t.Error("expected auto-generated Description='webapp container' to be set")
	}
}

func TestContainerSpec_Render_DescriptionNotOverridden(t *testing.T) {
	spec := &ContainerSpec{
		Name: "webapp",
		Unit: map[string]map[string]UnitValue{
			"Unit": {
				"Description": UV("Custom webapp description"), // User-specified description
			},
			"Container": {
				"Image": UV("nginx:latest"),
			},
		},
	}

	rendered, err := spec.Render("/etc/containers/config")
	if err != nil {
		t.Fatalf("Render failed: %v", err)
	}

	// Verify user-specified Description is preserved
	descriptionCount := 0
	for _, opt := range rendered.UnitOptions {
		if opt.Section == "Unit" && opt.Name == "Description" {
			descriptionCount++
			if opt.Value != "Custom webapp description" {
				t.Errorf("expected 'Custom webapp description', got %q", opt.Value)
			}
		}
	}
	if descriptionCount != 1 {
		t.Errorf("expected exactly 1 Description, got %d", descriptionCount)
	}
}

func TestContainerSpec_Unmarshal_InvalidUnit_Number(t *testing.T) {
	jsonData := []byte(`{
		"name": "webapp",
		"type": "container",
		"unit": {
			"Container": {
				"Port": 8080
			}
		}
	}`)

	var spec ContainerSpec
	err := json.Unmarshal(jsonData, &spec)
	if err == nil {
		t.Error("expected unmarshal to fail with numeric value, but it succeeded")
	}
}

func TestContainerSpec_Unmarshal_InvalidUnit_Boolean(t *testing.T) {
	jsonData := []byte(`{
		"name": "webapp",
		"type": "container",
		"unit": {
			"Container": {
				"Enabled": true
			}
		}
	}`)

	var spec ContainerSpec
	err := json.Unmarshal(jsonData, &spec)
	if err == nil {
		t.Error("expected unmarshal to fail with boolean value, but it succeeded")
	}
}

func TestContainerSpec_Unmarshal_InvalidUnit_ArrayWithNumber(t *testing.T) {
	jsonData := []byte(`{
		"name": "webapp",
		"type": "container",
		"unit": {
			"Container": {
				"Image": [123, 456]
			}
		}
	}`)

	var spec ContainerSpec
	err := json.Unmarshal(jsonData, &spec)
	if err == nil {
		t.Error("expected unmarshal to fail with array of numbers, but it succeeded")
	}
}

func TestContainerSpec_Render_WithRemovalAllowed(t *testing.T) {
	spec := &ContainerSpec{
		Name: "webapp",
		Unit: map[string]map[string]UnitValue{
			"Container": {"Image": UV("nginx:latest")},
		},
		RemovalAllowed: true,
	}

	rendered, err := spec.Render("/etc/containers/config")
	if err != nil {
		t.Fatalf("Render failed: %v", err)
	}

	// Verify RemovalAllowed is in X-Syslet section and comes first
	if len(rendered.UnitOptions) == 0 {
		t.Fatal("expected at least one unit option")
	}
	firstOpt := rendered.UnitOptions[0]
	if firstOpt.Section != "X-Syslet" || firstOpt.Name != "RemovalAllowed" || firstOpt.Value != "true" {
		t.Errorf("expected first option to be X-Syslet.RemovalAllowed=true, got %v.%v=%v",
			firstOpt.Section, firstOpt.Name, firstOpt.Value)
	}
}

func TestContainerSpec_Render_WithoutRemovalAllowed(t *testing.T) {
	spec := &ContainerSpec{
		Name: "webapp",
		Unit: map[string]map[string]UnitValue{
			"Container": {"Image": UV("nginx:latest")},
		},
		RemovalAllowed: false,
	}

	rendered, err := spec.Render("/etc/containers/config")
	if err != nil {
		t.Fatalf("Render failed: %v", err)
	}

	// Verify X-Syslet.RemovalAllowed is NOT present
	for _, opt := range rendered.UnitOptions {
		if opt.Section == "X-Syslet" && opt.Name == "RemovalAllowed" {
			t.Error("expected RemovalAllowed to not be rendered when false")
		}
	}
}

func TestContainerSpec_ShouldRemoveOnPrune_WithMarker(t *testing.T) {
	spec := &ContainerSpec{Name: "webapp"}

	// Create a unit file with RemovalAllowed=true
	fs := afero.NewMemMapFs()
	mockConn := &mockDBusConn{}
	sd := systemd.NewClient(mockConn, fs)

	// Create unit content with X-Syslet section
	opts := []*gounit.UnitOption{
		{Section: "X-Syslet", Name: "RemovalAllowed", Value: "true"},
		{Section: "Container", Name: "ContainerName", Value: "webapp"},
	}
	content := gounit.Serialize(opts)
	contentBytes := new(bytes.Buffer)
	_, _ = contentBytes.ReadFrom(content)

	_ = sd.WriteUnitFile("webapp.container", contentBytes.Bytes())

	if !spec.ShouldRemoveOnPrune(sd) {
		t.Error("expected ShouldRemoveOnPrune to return true when marker is present")
	}
}

func TestContainerSpec_ShouldRemoveOnPrune_WithoutMarker(t *testing.T) {
	spec := &ContainerSpec{Name: "webapp"}

	fs := afero.NewMemMapFs()
	mockConn := &mockDBusConn{}
	sd := systemd.NewClient(mockConn, fs)

	// Create unit content without RemovalAllowed
	opts := []*gounit.UnitOption{
		{Section: "Container", Name: "ContainerName", Value: "webapp"},
	}
	content := gounit.Serialize(opts)
	contentBytes := new(bytes.Buffer)
	_, _ = contentBytes.ReadFrom(content)

	_ = sd.WriteUnitFile("webapp.container", contentBytes.Bytes())

	if spec.ShouldRemoveOnPrune(sd) {
		t.Error("expected ShouldRemoveOnPrune to return false when marker is not present")
	}
}

func TestContainerSpec_ShouldRemoveOnPrune_FileNotFound(t *testing.T) {
	spec := &ContainerSpec{Name: "nonexistent"}

	fs := afero.NewMemMapFs()
	mockConn := &mockDBusConn{}
	sd := systemd.NewClient(mockConn, fs)

	if spec.ShouldRemoveOnPrune(sd) {
		t.Error("expected ShouldRemoveOnPrune to return false when file doesn't exist")
	}
}

func TestContainerSpec_ShouldRemoveOnPrune_CaseInsensitive(t *testing.T) {
	spec := &ContainerSpec{Name: "webapp"}

	fs := afero.NewMemMapFs()
	mockConn := &mockDBusConn{}
	sd := systemd.NewClient(mockConn, fs)

	// Create unit content with uppercase "TRUE"
	opts := []*gounit.UnitOption{
		{Section: "X-Syslet", Name: "RemovalAllowed", Value: "TRUE"},
		{Section: "Container", Name: "ContainerName", Value: "webapp"},
	}
	content := gounit.Serialize(opts)
	contentBytes := new(bytes.Buffer)
	_, _ = contentBytes.ReadFrom(content)

	_ = sd.WriteUnitFile("webapp.container", contentBytes.Bytes())

	if !spec.ShouldRemoveOnPrune(sd) {
		t.Error("expected ShouldRemoveOnPrune to be case-insensitive")
	}
}
