// Package model defines the domain types for systemd quadlet units (Container,
// Build, Network, Volume) and shared primitives such as UnitType and UnitRef.
package model

import (
	"encoding/json"
	"fmt"
	"sort"
)

// UnitType identifies the kind of systemd quadlet unit.
type UnitType string

// FileExtension returns the systemd unit file extension for this unit type (e.g. ".container").
func (t UnitType) FileExtension() string {
	return "." + string(t)
}

// ServiceUnitName is the systemd service unit name generated by quadlet
// (e.g. "webapp.service", "frontend-network.service").
type ServiceUnitName string

// UnitRef is implemented by the typed base name of every unit kind.
// It derives the full filename and spec type from the base name alone.
type UnitRef interface {
	// base name, e.g. "webapp"
	Name() string

	// base name plus unit type extension
	FullName() FullUnitName

	// unit type
	UnitType() UnitType

	// systemd service unit name generated by quadlet
	ServiceUnitName() ServiceUnitName
}

// ParseFullUnitName parses a full unit filename (e.g. "webapp.container") into
// the appropriate typed Unit based on its extension.
func ParseFullUnitName(name FullUnitName) (UnitRef, error) {
	base := name.Base()
	switch name.Suffix() {
	case string(UnitTypeContainer):
		return ContainerUnitRef(base), nil
	case string(UnitTypeBuild):
		return BuildUnitRef(base), nil
	case string(UnitTypeVolume):
		return VolumeUnitRef(base), nil
	case string(UnitTypeNetwork):
		return NetworkUnitRef(base), nil
	default:
		return nil, fmt.Errorf("unknown unit file extension: %q", name)
	}
}

// FullUnitName is the complete filename of a systemd  unit (e.g. "webapp.container").
// Using a named type prevents mixing base names and full names at call sites.
type FullUnitName string

// Suffix returns the file extension without the dot (e.g. "container" from "webapp.container").
func (n FullUnitName) Suffix() string {
	s := string(n)
	for i := len(s) - 1; i >= 0; i-- {
		if s[i] == '.' {
			return s[i+1:]
		}
	}
	return ""
}

// Base returns the name without the extension (e.g. "webapp" from "webapp.container").
func (n FullUnitName) Base() string {
	s := string(n)
	for i := len(s) - 1; i >= 0; i-- {
		if s[i] == '.' {
			return s[:i]
		}
	}
	return s
}

// SectionName is the typed section identifier for systemd unit files.
type SectionName string

// SectionKey is the typed key identifier within a systemd unit file section.
type SectionKey string

// UnitOptions maps systemd unit sections to their key-value pairs.
type UnitOptions map[SectionName]map[SectionKey]UnitValue

// UnitValue represents a value in a systemd unit specification.
// Systemd unit files only support string values; some options can appear multiple
// times (e.g. Volume=, PublishPort=), which is represented as a slice.
type UnitValue struct {
	values []string
}

// UV constructs a UnitValue from a single string, used in testing.
func UV(value string) UnitValue {
	return UnitValue{values: []string{value}}
}

// MultiUV constructs a UnitValue from multiple strings (e.g. for Network=, Volume=), used in testing.
func MultiUV(values ...string) UnitValue {
	cp := make([]string, len(values))
	copy(cp, values)
	return UnitValue{values: cp}
}

// EnvironmentKey is the systemd unit key that accepts map input in
// UnitValueFromRaw as name-to-value assignments (e.g. Environment=foo=bar).
const EnvironmentKey = SectionKey("Environment")

// ContainerSection is the [Container] section of a .container unit.
const ContainerSection = SectionName("Container")

// VolumeKey is the systemd unit key that accepts map input in UnitValueFromRaw
// as mount-to-source assignments (e.g. Volume=data:/var/lib/data).
const VolumeKey = SectionKey("Volume")

// SecretKey is the systemd unit key that accepts map input in UnitValueFromRaw
// as secret-name-to-options assignments (e.g. Secret=mysecret,type=mount).
const SecretKey = SectionKey("Secret")

// MaskKey is the systemd unit key that accepts map input in UnitValueFromRaw
// as path-to-value assignments (e.g. Mask=/proc/foo:/proc/bar).
const MaskKey = SectionKey("Mask")

// LogOptKey is the systemd unit key that accepts map input in UnitValueFromRaw
// as log-option-to-value assignments (e.g. LogOpt=path=/var/log/foo).
const LogOptKey = SectionKey("LogOpt")

// NetworkKey is the systemd unit key that accepts map input in UnitValueFromRaw
// as a set of network names; map values are ignored, only keys are used
// (e.g. Network=mynet).
const NetworkKey = SectionKey("Network")

// mapEntrySpec describes how a map entry's key (and, unless keyOnly, its
// string value) is formatted into a single unit value string.
type mapEntrySpec struct {
	separator string
	keyOnly   bool
	// valueOptional allows an empty string value, in which case the separator
	// and value are omitted entirely, leaving just the key (e.g. Secret).
	valueOptional bool
	// allowEmptyValue allows an empty string value, keeping the separator so
	// the key is still joined to the (empty) value (e.g. Environment=NAME=).
	// Ignored when valueOptional is set.
	allowEmptyValue bool
	// When both valueOptional and allowEmptyValue are false, an empty value is
	// a validation error since the separator would otherwise have no value to join.
}

// mapEntrySpecFor returns the mapEntrySpec for a given section/key
// combination, and whether that combination accepts map input at all.
func mapEntrySpecFor(section SectionName, key SectionKey) (mapEntrySpec, bool) {
	switch {
	case key == EnvironmentKey:
		// Environment=NAME=VALUE — map key is the variable name, map value is
		// its value. The value may be empty (Environment=NAME= sets it to the
		// empty string), so the separator is always kept.
		return mapEntrySpec{separator: "=", allowEmptyValue: true}, true
	case section == ContainerSection && key == VolumeKey:
		// Volume=SOURCE:DESTINATION[:OPTIONS] — map key is the host path or
		// named volume (mount source), map value is the in-container mount
		// path (optionally followed by its own ":OPTIONS" suffix).
		return mapEntrySpec{separator: ":"}, true
	case section == ContainerSection && key == SecretKey:
		// Secret=NAME,OPT=VAL,... — map key is the secret name, map value is the
		// remaining comma-separated option string appended after the name.
		// The options are optional, so an empty value omits the trailing comma.
		return mapEntrySpec{separator: ",", valueOptional: true}, true
	case section == ContainerSection && key == MaskKey:
		// Mask=PATH:PATH — map key is the path to mask, map value is the
		// path it is masked with.
		return mapEntrySpec{separator: ":"}, true
	case section == ContainerSection && key == LogOptKey:
		// LogOpt=OPTION=VALUE — map key is a log driver option name (e.g.
		// "path", "max-size"), map value is that option's value.
		return mapEntrySpec{separator: "="}, true
	case section == ContainerSection && key == NetworkKey:
		// Network=NAME — map key is the network name to join; there is no
		// per-network value in this field, so the map value is ignored.
		return mapEntrySpec{keyOnly: true}, true
	default:
		return mapEntrySpec{}, false
	}
}

// UnitValueFromRaw converts a value decoded by encoding/json (string or []any,
// plus map[string]any for section/key combinations accepted by
// mapEntrySpecFor) into a UnitValue. A map is converted to a list of
// "key<separator>value" entries (or just "key" for a keyOnly spec) sorted by
// key for deterministic output. Returns an error for any non-string element
// or, unless keyOnly, non-string map value.
func UnitValueFromRaw(section SectionName, key SectionKey, raw any) (UnitValue, error) {
	switch v := raw.(type) {
	case string:
		return UnitValue{values: []string{v}}, nil
	case []any:
		strs := make([]string, len(v))
		for i, elem := range v {
			s, ok := elem.(string)
			if !ok {
				return UnitValue{}, fmt.Errorf("unit value array element %d must be a string, got %T", i, elem)
			}
			strs[i] = s
		}
		return UnitValue{values: strs}, nil
	case map[string]any:
		spec, ok := mapEntrySpecFor(section, key)
		if !ok {
			return UnitValue{}, fmt.Errorf("unit value must be a string or array of strings, got %T (map input is not supported for [%s] %s)", raw, section, key)
		}
		keys := make([]string, 0, len(v))
		for k := range v {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		strs := make([]string, len(keys))
		for i, k := range keys {
			if spec.keyOnly {
				strs[i] = k
				continue
			}
			s, ok := v[k].(string)
			if !ok {
				return UnitValue{}, fmt.Errorf("unit value map entry %q must be a string, got %T", k, v[k])
			}
			if s == "" && !spec.valueOptional && !spec.allowEmptyValue {
				return UnitValue{}, fmt.Errorf("unit value map entry %q must not be empty", k)
			}
			if s == "" && spec.valueOptional {
				strs[i] = k
				continue
			}
			strs[i] = k + spec.separator + s
		}
		return UnitValue{values: strs}, nil
	default:
		return UnitValue{}, fmt.Errorf("unit value must be a string, array of strings, or map of strings, got %T", raw)
	}
}

// Values returns the underlying string values.
func (uv UnitValue) Values() []string {
	if uv.values == nil {
		return []string{}
	}
	return uv.values
}

// MarshalJSON serializes as a single string when there is one value, otherwise as []string.
func (uv UnitValue) MarshalJSON() ([]byte, error) {
	if len(uv.values) == 1 {
		return json.Marshal(uv.values[0])
	}
	return json.Marshal(uv.values)
}

// Unit is the interface implemented by all domain unit types.
// Each unit maps to a Podman quadlet file (.container, .volume, .network, .build).
type Unit interface {
	Ref() UnitRef
	Options() UnitOptions
}
