// Package model defines the domain types for systemd quadlet units (Container,
// Build, Network, Volume) and shared primitives such as UnitType and UnitRef.
package model

import (
	"encoding/json"
	"fmt"
)

// UnitType identifies the kind of systemd quadlet unit.
type UnitType string

// FileExtension returns the systemd unit file extension for this unit type (e.g. ".container").
func (t UnitType) FileExtension() string {
	return "." + string(t)
}

// ServiceUnitName is the systemd service unit name generated by quadlet
// (e.g. "webapp.service", "frontend-network.service").
type ServiceUnitName string

// UnitRef is implemented by the typed base name of every unit kind.
// It derives the full filename and spec type from the base name alone.
type UnitRef interface {
	// base name, e.g. "webapp"
	Name() string

	// base name plus unit type extension
	FullName() FullUnitName

	// unit type
	UnitType() UnitType

	// systemd service unit name generated by quadlet
	ServiceUnitName() ServiceUnitName
}

// ParseFullUnitName parses a full unit filename (e.g. "webapp.container") into
// the appropriate typed Unit based on its extension.
func ParseFullUnitName(name FullUnitName) (UnitRef, error) {
	base := name.Base()
	switch name.Suffix() {
	case string(UnitTypeContainer):
		return ContainerUnitRef(base), nil
	case string(UnitTypeBuild):
		return BuildUnitRef(base), nil
	case string(UnitTypeVolume):
		return VolumeUnitRef(base), nil
	case string(UnitTypeNetwork):
		return NetworkUnitRef(base), nil
	default:
		return nil, fmt.Errorf("unknown unit file extension: %q", name)
	}
}

// FullUnitName is the complete filename of a systemd  unit (e.g. "webapp.container").
// Using a named type prevents mixing base names and full names at call sites.
type FullUnitName string

// Suffix returns the file extension without the dot (e.g. "container" from "webapp.container").
func (n FullUnitName) Suffix() string {
	s := string(n)
	for i := len(s) - 1; i >= 0; i-- {
		if s[i] == '.' {
			return s[i+1:]
		}
	}
	return ""
}

// Base returns the name without the extension (e.g. "webapp" from "webapp.container").
func (n FullUnitName) Base() string {
	s := string(n)
	for i := len(s) - 1; i >= 0; i-- {
		if s[i] == '.' {
			return s[:i]
		}
	}
	return s
}

// SectionName is the typed section identifier for systemd unit files.
type SectionName string

// SectionKey is the typed key identifier within a systemd unit file section.
type SectionKey string

// UnitOptions maps systemd unit sections to their key-value pairs.
type UnitOptions map[SectionName]map[SectionKey]UnitValue

// UnitValue represents a value in a systemd unit specification.
// Systemd unit files only support string values; some options can appear multiple
// times (e.g. Volume=, PublishPort=), which is represented as a slice.
type UnitValue struct {
	values []string
}

// UV constructs a UnitValue from a single string, used in testing.
func UV(value string) UnitValue {
	return UnitValue{values: []string{value}}
}

// MultiUV constructs a UnitValue from multiple strings (e.g. for Network=, Volume=), used in testing.
func MultiUV(values ...string) UnitValue {
	cp := make([]string, len(values))
	copy(cp, values)
	return UnitValue{values: cp}
}

// UnitValueFromRaw converts a value decoded by encoding/json (string or []any)
// into a UnitValue. Returns an error for any non-string element.
func UnitValueFromRaw(raw any) (UnitValue, error) {
	switch v := raw.(type) {
	case string:
		return UnitValue{values: []string{v}}, nil
	case []any:
		strs := make([]string, len(v))
		for i, elem := range v {
			s, ok := elem.(string)
			if !ok {
				return UnitValue{}, fmt.Errorf("unit value array element %d must be a string, got %T", i, elem)
			}
			strs[i] = s
		}
		return UnitValue{values: strs}, nil
	default:
		return UnitValue{}, fmt.Errorf("unit value must be a string or array of strings, got %T", raw)
	}
}

// Values returns the underlying string values.
func (uv UnitValue) Values() []string {
	if uv.values == nil {
		return []string{}
	}
	return uv.values
}

// MarshalJSON serializes as a single string when there is one value, otherwise as []string.
func (uv UnitValue) MarshalJSON() ([]byte, error) {
	if len(uv.values) == 1 {
		return json.Marshal(uv.values[0])
	}
	return json.Marshal(uv.values)
}

// Unit is the interface implemented by all domain unit types.
// Each unit maps to a Podman quadlet file (.container, .volume, .network, .build).
type Unit interface {
	Ref() UnitRef
	Options() UnitOptions
}
