// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: proto/rsystemd.proto

package rsystemdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnitType int32

const (
	UnitType_UNIT_TYPE_UNSPECIFIED UnitType = 0
	UnitType_UNIT_TYPE_CONTAINER   UnitType = 3
	UnitType_UNIT_TYPE_VOLUME      UnitType = 4
	UnitType_UNIT_TYPE_NETWORK     UnitType = 5
)

// Enum value maps for UnitType.
var (
	UnitType_name = map[int32]string{
		0: "UNIT_TYPE_UNSPECIFIED",
		3: "UNIT_TYPE_CONTAINER",
		4: "UNIT_TYPE_VOLUME",
		5: "UNIT_TYPE_NETWORK",
	}
	UnitType_value = map[string]int32{
		"UNIT_TYPE_UNSPECIFIED": 0,
		"UNIT_TYPE_CONTAINER":   3,
		"UNIT_TYPE_VOLUME":      4,
		"UNIT_TYPE_NETWORK":     5,
	}
)

func (x UnitType) Enum() *UnitType {
	p := new(UnitType)
	*p = x
	return p
}

func (x UnitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnitType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rsystemd_proto_enumTypes[0].Descriptor()
}

func (UnitType) Type() protoreflect.EnumType {
	return &file_proto_rsystemd_proto_enumTypes[0]
}

func (x UnitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnitType.Descriptor instead.
func (UnitType) EnumDescriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{0}
}

type DesiredState int32

const (
	DesiredState_DESIRED_STATE_UNSPECIFIED DesiredState = 0
	DesiredState_DESIRED_STATE_RUNNING     DesiredState = 1
	DesiredState_DESIRED_STATE_STOPPED     DesiredState = 2
)

// Enum value maps for DesiredState.
var (
	DesiredState_name = map[int32]string{
		0: "DESIRED_STATE_UNSPECIFIED",
		1: "DESIRED_STATE_RUNNING",
		2: "DESIRED_STATE_STOPPED",
	}
	DesiredState_value = map[string]int32{
		"DESIRED_STATE_UNSPECIFIED": 0,
		"DESIRED_STATE_RUNNING":     1,
		"DESIRED_STATE_STOPPED":     2,
	}
)

func (x DesiredState) Enum() *DesiredState {
	p := new(DesiredState)
	*p = x
	return p
}

func (x DesiredState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesiredState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rsystemd_proto_enumTypes[1].Descriptor()
}

func (DesiredState) Type() protoreflect.EnumType {
	return &file_proto_rsystemd_proto_enumTypes[1]
}

func (x DesiredState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesiredState.Descriptor instead.
func (DesiredState) EnumDescriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{1}
}

type ActiveState int32

const (
	ActiveState_ACTIVE_STATE_UNSPECIFIED  ActiveState = 0
	ActiveState_ACTIVE_STATE_ACTIVE       ActiveState = 1
	ActiveState_ACTIVE_STATE_INACTIVE     ActiveState = 2
	ActiveState_ACTIVE_STATE_FAILED       ActiveState = 3
	ActiveState_ACTIVE_STATE_ACTIVATING   ActiveState = 4
	ActiveState_ACTIVE_STATE_DEACTIVATING ActiveState = 5
)

// Enum value maps for ActiveState.
var (
	ActiveState_name = map[int32]string{
		0: "ACTIVE_STATE_UNSPECIFIED",
		1: "ACTIVE_STATE_ACTIVE",
		2: "ACTIVE_STATE_INACTIVE",
		3: "ACTIVE_STATE_FAILED",
		4: "ACTIVE_STATE_ACTIVATING",
		5: "ACTIVE_STATE_DEACTIVATING",
	}
	ActiveState_value = map[string]int32{
		"ACTIVE_STATE_UNSPECIFIED":  0,
		"ACTIVE_STATE_ACTIVE":       1,
		"ACTIVE_STATE_INACTIVE":     2,
		"ACTIVE_STATE_FAILED":       3,
		"ACTIVE_STATE_ACTIVATING":   4,
		"ACTIVE_STATE_DEACTIVATING": 5,
	}
)

func (x ActiveState) Enum() *ActiveState {
	p := new(ActiveState)
	*p = x
	return p
}

func (x ActiveState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActiveState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rsystemd_proto_enumTypes[2].Descriptor()
}

func (ActiveState) Type() protoreflect.EnumType {
	return &file_proto_rsystemd_proto_enumTypes[2]
}

func (x ActiveState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActiveState.Descriptor instead.
func (ActiveState) EnumDescriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{2}
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specs         []string               `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"` // JSON-encoded ContainerSpec documents
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_proto_rsystemd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetSpecs() []string {
	if x != nil {
		return x.Specs
	}
	return nil
}

type UnitResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          UnitType               `protobuf:"varint,2,opt,name=type,proto3,enum=rsystemd.v1.UnitType" json:"type,omitempty"`
	Changed       bool                   `protobuf:"varint,3,opt,name=changed,proto3" json:"changed,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitResult) Reset() {
	*x = UnitResult{}
	mi := &file_proto_rsystemd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitResult) ProtoMessage() {}

func (x *UnitResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitResult.ProtoReflect.Descriptor instead.
func (*UnitResult) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{1}
}

func (x *UnitResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitResult) GetType() UnitType {
	if x != nil {
		return x.Type
	}
	return UnitType_UNIT_TYPE_UNSPECIFIED
}

func (x *UnitResult) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *UnitResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*UnitResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_proto_rsystemd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyResponse) GetResults() []*UnitResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitName      string                 `protobuf:"bytes,1,opt,name=unit_name,json=unitName,proto3" json:"unit_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_rsystemd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{3}
}

func (x *StatusRequest) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

type UnitStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type           UnitType               `protobuf:"varint,2,opt,name=type,proto3,enum=rsystemd.v1.UnitType" json:"type,omitempty"`
	DesiredState   DesiredState           `protobuf:"varint,3,opt,name=desired_state,json=desiredState,proto3,enum=rsystemd.v1.DesiredState" json:"desired_state,omitempty"`
	ActiveState    ActiveState            `protobuf:"varint,4,opt,name=active_state,json=activeState,proto3,enum=rsystemd.v1.ActiveState" json:"active_state,omitempty"`
	Enabled        bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ConfigFiles    []string               `protobuf:"bytes,6,rep,name=config_files,json=configFiles,proto3" json:"config_files,omitempty"`
	LastReconciled string                 `protobuf:"bytes,7,opt,name=last_reconciled,json=lastReconciled,proto3" json:"last_reconciled,omitempty"`
	Error          string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnitStatus) Reset() {
	*x = UnitStatus{}
	mi := &file_proto_rsystemd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitStatus) ProtoMessage() {}

func (x *UnitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitStatus.ProtoReflect.Descriptor instead.
func (*UnitStatus) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{4}
}

func (x *UnitStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitStatus) GetType() UnitType {
	if x != nil {
		return x.Type
	}
	return UnitType_UNIT_TYPE_UNSPECIFIED
}

func (x *UnitStatus) GetDesiredState() DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return DesiredState_DESIRED_STATE_UNSPECIFIED
}

func (x *UnitStatus) GetActiveState() ActiveState {
	if x != nil {
		return x.ActiveState
	}
	return ActiveState_ACTIVE_STATE_UNSPECIFIED
}

func (x *UnitStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UnitStatus) GetConfigFiles() []string {
	if x != nil {
		return x.ConfigFiles
	}
	return nil
}

func (x *UnitStatus) GetLastReconciled() string {
	if x != nil {
		return x.LastReconciled
	}
	return ""
}

func (x *UnitStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*UnitStatus          `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_rsystemd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetUnits() []*UnitStatus {
	if x != nil {
		return x.Units
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeFilter    UnitType               `protobuf:"varint,1,opt,name=type_filter,json=typeFilter,proto3,enum=rsystemd.v1.UnitType" json:"type_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_rsystemd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetTypeFilter() UnitType {
	if x != nil {
		return x.TypeFilter
	}
	return UnitType_UNIT_TYPE_UNSPECIFIED
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*UnitStatus          `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_rsystemd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetUnits() []*UnitStatus {
	if x != nil {
		return x.Units
	}
	return nil
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitName      string                 `protobuf:"bytes,1,opt,name=unit_name,json=unitName,proto3" json:"unit_name,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	Lines         int32                  `protobuf:"varint,3,opt,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_proto_rsystemd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{8}
}

func (x *LogsRequest) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_rsystemd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{9}
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitName      string                 `protobuf:"bytes,1,opt,name=unit_name,json=unitName,proto3" json:"unit_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_rsystemd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_rsystemd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rsystemd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_rsystemd_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_rsystemd_proto protoreflect.FileDescriptor

const file_proto_rsystemd_proto_rawDesc = "" +
	"\n" +
	"\x14proto/rsystemd.proto\x12\vrsystemd.v1\"$\n" +
	"\fApplyRequest\x12\x14\n" +
	"\x05specs\x18\x01 \x03(\tR\x05specs\"\x7f\n" +
	"\n" +
	"UnitResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.rsystemd.v1.UnitTypeR\x04type\x12\x18\n" +
	"\achanged\x18\x03 \x01(\bR\achanged\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"B\n" +
	"\rApplyResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.rsystemd.v1.UnitResultR\aresults\",\n" +
	"\rStatusRequest\x12\x1b\n" +
	"\tunit_name\x18\x01 \x01(\tR\bunitName\"\xc4\x02\n" +
	"\n" +
	"UnitStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.rsystemd.v1.UnitTypeR\x04type\x12>\n" +
	"\rdesired_state\x18\x03 \x01(\x0e2\x19.rsystemd.v1.DesiredStateR\fdesiredState\x12;\n" +
	"\factive_state\x18\x04 \x01(\x0e2\x18.rsystemd.v1.ActiveStateR\vactiveState\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12!\n" +
	"\fconfig_files\x18\x06 \x03(\tR\vconfigFiles\x12'\n" +
	"\x0flast_reconciled\x18\a \x01(\tR\x0elastReconciled\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"?\n" +
	"\x0eStatusResponse\x12-\n" +
	"\x05units\x18\x01 \x03(\v2\x17.rsystemd.v1.UnitStatusR\x05units\"E\n" +
	"\vListRequest\x126\n" +
	"\vtype_filter\x18\x01 \x01(\x0e2\x15.rsystemd.v1.UnitTypeR\n" +
	"typeFilter\"=\n" +
	"\fListResponse\x12-\n" +
	"\x05units\x18\x01 \x03(\v2\x17.rsystemd.v1.UnitStatusR\x05units\"X\n" +
	"\vLogsRequest\x12\x1b\n" +
	"\tunit_name\x18\x01 \x01(\tR\bunitName\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x14\n" +
	"\x05lines\x18\x03 \x01(\x05R\x05lines\"^\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\",\n" +
	"\rDeleteRequest\x12\x1b\n" +
	"\tunit_name\x18\x01 \x01(\tR\bunitName\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*k\n" +
	"\bUnitType\x12\x19\n" +
	"\x15UNIT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13UNIT_TYPE_CONTAINER\x10\x03\x12\x14\n" +
	"\x10UNIT_TYPE_VOLUME\x10\x04\x12\x15\n" +
	"\x11UNIT_TYPE_NETWORK\x10\x05*c\n" +
	"\fDesiredState\x12\x1d\n" +
	"\x19DESIRED_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DESIRED_STATE_RUNNING\x10\x01\x12\x19\n" +
	"\x15DESIRED_STATE_STOPPED\x10\x02*\xb4\x01\n" +
	"\vActiveState\x12\x1c\n" +
	"\x18ACTIVE_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACTIVE_STATE_ACTIVE\x10\x01\x12\x19\n" +
	"\x15ACTIVE_STATE_INACTIVE\x10\x02\x12\x17\n" +
	"\x13ACTIVE_STATE_FAILED\x10\x03\x12\x1b\n" +
	"\x17ACTIVE_STATE_ACTIVATING\x10\x04\x12\x1d\n" +
	"\x19ACTIVE_STATE_DEACTIVATING\x10\x052\xcf\x02\n" +
	"\x0fRsystemdService\x12>\n" +
	"\x05Apply\x12\x19.rsystemd.v1.ApplyRequest\x1a\x1a.rsystemd.v1.ApplyResponse\x12A\n" +
	"\x06Status\x12\x1a.rsystemd.v1.StatusRequest\x1a\x1b.rsystemd.v1.StatusResponse\x12;\n" +
	"\x04List\x12\x18.rsystemd.v1.ListRequest\x1a\x19.rsystemd.v1.ListResponse\x129\n" +
	"\x04Logs\x12\x18.rsystemd.v1.LogsRequest\x1a\x15.rsystemd.v1.LogEntry0\x01\x12A\n" +
	"\x06Delete\x12\x1a.rsystemd.v1.DeleteRequest\x1a\x1b.rsystemd.v1.DeleteResponseB2Z0codeberg.org/xchangeee/rsystemd/proto;rsystemdv1b\x06proto3"

var (
	file_proto_rsystemd_proto_rawDescOnce sync.Once
	file_proto_rsystemd_proto_rawDescData []byte
)

func file_proto_rsystemd_proto_rawDescGZIP() []byte {
	file_proto_rsystemd_proto_rawDescOnce.Do(func() {
		file_proto_rsystemd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rsystemd_proto_rawDesc), len(file_proto_rsystemd_proto_rawDesc)))
	})
	return file_proto_rsystemd_proto_rawDescData
}

var file_proto_rsystemd_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_rsystemd_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_rsystemd_proto_goTypes = []any{
	(UnitType)(0),          // 0: rsystemd.v1.UnitType
	(DesiredState)(0),      // 1: rsystemd.v1.DesiredState
	(ActiveState)(0),       // 2: rsystemd.v1.ActiveState
	(*ApplyRequest)(nil),   // 3: rsystemd.v1.ApplyRequest
	(*UnitResult)(nil),     // 4: rsystemd.v1.UnitResult
	(*ApplyResponse)(nil),  // 5: rsystemd.v1.ApplyResponse
	(*StatusRequest)(nil),  // 6: rsystemd.v1.StatusRequest
	(*UnitStatus)(nil),     // 7: rsystemd.v1.UnitStatus
	(*StatusResponse)(nil), // 8: rsystemd.v1.StatusResponse
	(*ListRequest)(nil),    // 9: rsystemd.v1.ListRequest
	(*ListResponse)(nil),   // 10: rsystemd.v1.ListResponse
	(*LogsRequest)(nil),    // 11: rsystemd.v1.LogsRequest
	(*LogEntry)(nil),       // 12: rsystemd.v1.LogEntry
	(*DeleteRequest)(nil),  // 13: rsystemd.v1.DeleteRequest
	(*DeleteResponse)(nil), // 14: rsystemd.v1.DeleteResponse
}
var file_proto_rsystemd_proto_depIdxs = []int32{
	0,  // 0: rsystemd.v1.UnitResult.type:type_name -> rsystemd.v1.UnitType
	4,  // 1: rsystemd.v1.ApplyResponse.results:type_name -> rsystemd.v1.UnitResult
	0,  // 2: rsystemd.v1.UnitStatus.type:type_name -> rsystemd.v1.UnitType
	1,  // 3: rsystemd.v1.UnitStatus.desired_state:type_name -> rsystemd.v1.DesiredState
	2,  // 4: rsystemd.v1.UnitStatus.active_state:type_name -> rsystemd.v1.ActiveState
	7,  // 5: rsystemd.v1.StatusResponse.units:type_name -> rsystemd.v1.UnitStatus
	0,  // 6: rsystemd.v1.ListRequest.type_filter:type_name -> rsystemd.v1.UnitType
	7,  // 7: rsystemd.v1.ListResponse.units:type_name -> rsystemd.v1.UnitStatus
	3,  // 8: rsystemd.v1.RsystemdService.Apply:input_type -> rsystemd.v1.ApplyRequest
	6,  // 9: rsystemd.v1.RsystemdService.Status:input_type -> rsystemd.v1.StatusRequest
	9,  // 10: rsystemd.v1.RsystemdService.List:input_type -> rsystemd.v1.ListRequest
	11, // 11: rsystemd.v1.RsystemdService.Logs:input_type -> rsystemd.v1.LogsRequest
	13, // 12: rsystemd.v1.RsystemdService.Delete:input_type -> rsystemd.v1.DeleteRequest
	5,  // 13: rsystemd.v1.RsystemdService.Apply:output_type -> rsystemd.v1.ApplyResponse
	8,  // 14: rsystemd.v1.RsystemdService.Status:output_type -> rsystemd.v1.StatusResponse
	10, // 15: rsystemd.v1.RsystemdService.List:output_type -> rsystemd.v1.ListResponse
	12, // 16: rsystemd.v1.RsystemdService.Logs:output_type -> rsystemd.v1.LogEntry
	14, // 17: rsystemd.v1.RsystemdService.Delete:output_type -> rsystemd.v1.DeleteResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_rsystemd_proto_init() }
func file_proto_rsystemd_proto_init() {
	if File_proto_rsystemd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rsystemd_proto_rawDesc), len(file_proto_rsystemd_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rsystemd_proto_goTypes,
		DependencyIndexes: file_proto_rsystemd_proto_depIdxs,
		EnumInfos:         file_proto_rsystemd_proto_enumTypes,
		MessageInfos:      file_proto_rsystemd_proto_msgTypes,
	}.Build()
	File_proto_rsystemd_proto = out.File
	file_proto_rsystemd_proto_goTypes = nil
	file_proto_rsystemd_proto_depIdxs = nil
}
