// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/syslet.proto

package sysletv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DesiredState int32

const (
	DesiredState_DESIRED_STATE_UNSPECIFIED DesiredState = 0
	DesiredState_DESIRED_STATE_RUNNING     DesiredState = 1
	DesiredState_DESIRED_STATE_STOPPED     DesiredState = 2
)

// Enum value maps for DesiredState.
var (
	DesiredState_name = map[int32]string{
		0: "DESIRED_STATE_UNSPECIFIED",
		1: "DESIRED_STATE_RUNNING",
		2: "DESIRED_STATE_STOPPED",
	}
	DesiredState_value = map[string]int32{
		"DESIRED_STATE_UNSPECIFIED": 0,
		"DESIRED_STATE_RUNNING":     1,
		"DESIRED_STATE_STOPPED":     2,
	}
)

func (x DesiredState) Enum() *DesiredState {
	p := new(DesiredState)
	*p = x
	return p
}

func (x DesiredState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesiredState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_syslet_proto_enumTypes[0].Descriptor()
}

func (DesiredState) Type() protoreflect.EnumType {
	return &file_proto_syslet_proto_enumTypes[0]
}

func (x DesiredState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesiredState.Descriptor instead.
func (DesiredState) EnumDescriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{0}
}

type ActiveState int32

const (
	ActiveState_ACTIVE_STATE_UNSPECIFIED  ActiveState = 0
	ActiveState_ACTIVE_STATE_ACTIVE       ActiveState = 1
	ActiveState_ACTIVE_STATE_INACTIVE     ActiveState = 2
	ActiveState_ACTIVE_STATE_FAILED       ActiveState = 3
	ActiveState_ACTIVE_STATE_ACTIVATING   ActiveState = 4
	ActiveState_ACTIVE_STATE_DEACTIVATING ActiveState = 5
)

// Enum value maps for ActiveState.
var (
	ActiveState_name = map[int32]string{
		0: "ACTIVE_STATE_UNSPECIFIED",
		1: "ACTIVE_STATE_ACTIVE",
		2: "ACTIVE_STATE_INACTIVE",
		3: "ACTIVE_STATE_FAILED",
		4: "ACTIVE_STATE_ACTIVATING",
		5: "ACTIVE_STATE_DEACTIVATING",
	}
	ActiveState_value = map[string]int32{
		"ACTIVE_STATE_UNSPECIFIED":  0,
		"ACTIVE_STATE_ACTIVE":       1,
		"ACTIVE_STATE_INACTIVE":     2,
		"ACTIVE_STATE_FAILED":       3,
		"ACTIVE_STATE_ACTIVATING":   4,
		"ACTIVE_STATE_DEACTIVATING": 5,
	}
)

func (x ActiveState) Enum() *ActiveState {
	p := new(ActiveState)
	*p = x
	return p
}

func (x ActiveState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActiveState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_syslet_proto_enumTypes[1].Descriptor()
}

func (ActiveState) Type() protoreflect.EnumType {
	return &file_proto_syslet_proto_enumTypes[1]
}

func (x ActiveState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActiveState.Descriptor instead.
func (ActiveState) EnumDescriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{1}
}

type UnitOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitOption) Reset() {
	*x = UnitOption{}
	mi := &file_proto_syslet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitOption) ProtoMessage() {}

func (x *UnitOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitOption.ProtoReflect.Descriptor instead.
func (*UnitOption) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{0}
}

func (x *UnitOption) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *UnitOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ConfigEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TargetVolumePath string                 `protobuf:"bytes,2,opt,name=target_volume_path,json=targetVolumePath,proto3" json:"target_volume_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigEntry) Reset() {
	*x = ConfigEntry{}
	mi := &file_proto_syslet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigEntry) ProtoMessage() {}

func (x *ConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigEntry.ProtoReflect.Descriptor instead.
func (*ConfigEntry) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConfigEntry) GetTargetVolumePath() string {
	if x != nil {
		return x.TargetVolumePath
	}
	return ""
}

// Per-unit result returned from Apply RPCs.
type ApplyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Changed       bool                   `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResult) Reset() {
	*x = ApplyResult{}
	mi := &file_proto_syslet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResult) ProtoMessage() {}

func (x *ApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResult.ProtoReflect.Descriptor instead.
func (*ApplyResult) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplyResult) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *ApplyResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ContainerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DesiredState  DesiredState           `protobuf:"varint,2,opt,name=desired_state,json=desiredState,proto3,enum=syslet.v1.DesiredState" json:"desired_state,omitempty"`
	Options       []*UnitOption          `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	Configs       []*ConfigEntry         `protobuf:"bytes,4,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_proto_syslet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerSpec) GetDesiredState() DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return DesiredState_DESIRED_STATE_UNSPECIFIED
}

func (x *ContainerSpec) GetOptions() []*UnitOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ContainerSpec) GetConfigs() []*ConfigEntry {
	if x != nil {
		return x.Configs
	}
	return nil
}

type VolumeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Options       []*UnitOption          `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeSpec) Reset() {
	*x = VolumeSpec{}
	mi := &file_proto_syslet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeSpec) ProtoMessage() {}

func (x *VolumeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeSpec.ProtoReflect.Descriptor instead.
func (*VolumeSpec) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{4}
}

func (x *VolumeSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeSpec) GetOptions() []*UnitOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type NetworkSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Options       []*UnitOption          `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkSpec) Reset() {
	*x = NetworkSpec{}
	mi := &file_proto_syslet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSpec) ProtoMessage() {}

func (x *NetworkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSpec.ProtoReflect.Descriptor instead.
func (*NetworkSpec) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkSpec) GetOptions() []*UnitOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type ApplyContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specs         []*ContainerSpec       `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyContainersRequest) Reset() {
	*x = ApplyContainersRequest{}
	mi := &file_proto_syslet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyContainersRequest) ProtoMessage() {}

func (x *ApplyContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyContainersRequest.ProtoReflect.Descriptor instead.
func (*ApplyContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyContainersRequest) GetSpecs() []*ContainerSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

type ApplyContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ApplyResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyContainersResponse) Reset() {
	*x = ApplyContainersResponse{}
	mi := &file_proto_syslet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyContainersResponse) ProtoMessage() {}

func (x *ApplyContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyContainersResponse.ProtoReflect.Descriptor instead.
func (*ApplyContainersResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyContainersResponse) GetResults() []*ApplyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerRequest) Reset() {
	*x = GetContainerRequest{}
	mi := &file_proto_syslet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerRequest) ProtoMessage() {}

func (x *GetContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerRequest.ProtoReflect.Descriptor instead.
func (*GetContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{8}
}

func (x *GetContainerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Container     *ContainerStatus       `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerResponse) Reset() {
	*x = GetContainerResponse{}
	mi := &file_proto_syslet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerResponse) ProtoMessage() {}

func (x *GetContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerResponse.ProtoReflect.Descriptor instead.
func (*GetContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{9}
}

func (x *GetContainerResponse) GetContainer() *ContainerStatus {
	if x != nil {
		return x.Container
	}
	return nil
}

type ListContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_proto_syslet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{10}
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerStatus     `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_proto_syslet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{11}
}

func (x *ListContainersResponse) GetContainers() []*ContainerStatus {
	if x != nil {
		return x.Containers
	}
	return nil
}

type DeleteContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContainerRequest) Reset() {
	*x = DeleteContainerRequest{}
	mi := &file_proto_syslet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerRequest) ProtoMessage() {}

func (x *DeleteContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerRequest.ProtoReflect.Descriptor instead.
func (*DeleteContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteContainerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContainerResponse) Reset() {
	*x = DeleteContainerResponse{}
	mi := &file_proto_syslet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerResponse) ProtoMessage() {}

func (x *DeleteContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerResponse.ProtoReflect.Descriptor instead.
func (*DeleteContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteContainerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApplyVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specs         []*VolumeSpec          `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyVolumesRequest) Reset() {
	*x = ApplyVolumesRequest{}
	mi := &file_proto_syslet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyVolumesRequest) ProtoMessage() {}

func (x *ApplyVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyVolumesRequest.ProtoReflect.Descriptor instead.
func (*ApplyVolumesRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{14}
}

func (x *ApplyVolumesRequest) GetSpecs() []*VolumeSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

type ApplyVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ApplyResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyVolumesResponse) Reset() {
	*x = ApplyVolumesResponse{}
	mi := &file_proto_syslet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyVolumesResponse) ProtoMessage() {}

func (x *ApplyVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyVolumesResponse.ProtoReflect.Descriptor instead.
func (*ApplyVolumesResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{15}
}

func (x *ApplyVolumesResponse) GetResults() []*ApplyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeRequest) Reset() {
	*x = GetVolumeRequest{}
	mi := &file_proto_syslet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeRequest) ProtoMessage() {}

func (x *GetVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeRequest.ProtoReflect.Descriptor instead.
func (*GetVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{16}
}

func (x *GetVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        *VolumeStatus          `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeResponse) Reset() {
	*x = GetVolumeResponse{}
	mi := &file_proto_syslet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeResponse) ProtoMessage() {}

func (x *GetVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeResponse.ProtoReflect.Descriptor instead.
func (*GetVolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{17}
}

func (x *GetVolumeResponse) GetVolume() *VolumeStatus {
	if x != nil {
		return x.Volume
	}
	return nil
}

type ListVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesRequest) Reset() {
	*x = ListVolumesRequest{}
	mi := &file_proto_syslet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesRequest) ProtoMessage() {}

func (x *ListVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesRequest.ProtoReflect.Descriptor instead.
func (*ListVolumesRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{18}
}

type ListVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*VolumeStatus        `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesResponse) Reset() {
	*x = ListVolumesResponse{}
	mi := &file_proto_syslet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesResponse) ProtoMessage() {}

func (x *ListVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesResponse.ProtoReflect.Descriptor instead.
func (*ListVolumesResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{19}
}

func (x *ListVolumesResponse) GetVolumes() []*VolumeStatus {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type DeleteVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeRequest) Reset() {
	*x = DeleteVolumeRequest{}
	mi := &file_proto_syslet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeRequest) ProtoMessage() {}

func (x *DeleteVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeResponse) Reset() {
	*x = DeleteVolumeResponse{}
	mi := &file_proto_syslet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeResponse) ProtoMessage() {}

func (x *DeleteVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeResponse.ProtoReflect.Descriptor instead.
func (*DeleteVolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteVolumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApplyNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specs         []*NetworkSpec         `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyNetworksRequest) Reset() {
	*x = ApplyNetworksRequest{}
	mi := &file_proto_syslet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyNetworksRequest) ProtoMessage() {}

func (x *ApplyNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyNetworksRequest.ProtoReflect.Descriptor instead.
func (*ApplyNetworksRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{22}
}

func (x *ApplyNetworksRequest) GetSpecs() []*NetworkSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

type ApplyNetworksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ApplyResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyNetworksResponse) Reset() {
	*x = ApplyNetworksResponse{}
	mi := &file_proto_syslet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyNetworksResponse) ProtoMessage() {}

func (x *ApplyNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyNetworksResponse.ProtoReflect.Descriptor instead.
func (*ApplyNetworksResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{23}
}

func (x *ApplyNetworksResponse) GetResults() []*ApplyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkRequest) Reset() {
	*x = GetNetworkRequest{}
	mi := &file_proto_syslet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkRequest) ProtoMessage() {}

func (x *GetNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{24}
}

func (x *GetNetworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       *NetworkStatus         `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkResponse) Reset() {
	*x = GetNetworkResponse{}
	mi := &file_proto_syslet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkResponse) ProtoMessage() {}

func (x *GetNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{25}
}

func (x *GetNetworkResponse) GetNetwork() *NetworkStatus {
	if x != nil {
		return x.Network
	}
	return nil
}

type ListNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksRequest) Reset() {
	*x = ListNetworksRequest{}
	mi := &file_proto_syslet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksRequest) ProtoMessage() {}

func (x *ListNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksRequest.ProtoReflect.Descriptor instead.
func (*ListNetworksRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{26}
}

type ListNetworksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*NetworkStatus       `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworksResponse) Reset() {
	*x = ListNetworksResponse{}
	mi := &file_proto_syslet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworksResponse) ProtoMessage() {}

func (x *ListNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworksResponse.ProtoReflect.Descriptor instead.
func (*ListNetworksResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{27}
}

func (x *ListNetworksResponse) GetNetworks() []*NetworkStatus {
	if x != nil {
		return x.Networks
	}
	return nil
}

type DeleteNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkRequest) Reset() {
	*x = DeleteNetworkRequest{}
	mi := &file_proto_syslet_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkRequest) ProtoMessage() {}

func (x *DeleteNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteNetworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkResponse) Reset() {
	*x = DeleteNetworkResponse{}
	mi := &file_proto_syslet_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkResponse) ProtoMessage() {}

func (x *DeleteNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkResponse.ProtoReflect.Descriptor instead.
func (*DeleteNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteNetworkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ContainerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ActiveState   ActiveState            `protobuf:"varint,3,opt,name=active_state,json=activeState,proto3,enum=syslet.v1.ActiveState" json:"active_state,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ConfigFiles   []string               `protobuf:"bytes,5,rep,name=config_files,json=configFiles,proto3" json:"config_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatus) Reset() {
	*x = ContainerStatus{}
	mi := &file_proto_syslet_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatus) ProtoMessage() {}

func (x *ContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatus.ProtoReflect.Descriptor instead.
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{30}
}

func (x *ContainerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerStatus) GetActiveState() ActiveState {
	if x != nil {
		return x.ActiveState
	}
	return ActiveState_ACTIVE_STATE_UNSPECIFIED
}

func (x *ContainerStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ContainerStatus) GetConfigFiles() []string {
	if x != nil {
		return x.ConfigFiles
	}
	return nil
}

type VolumeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ActiveState   ActiveState            `protobuf:"varint,2,opt,name=active_state,json=activeState,proto3,enum=syslet.v1.ActiveState" json:"active_state,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeStatus) Reset() {
	*x = VolumeStatus{}
	mi := &file_proto_syslet_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeStatus) ProtoMessage() {}

func (x *VolumeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeStatus.ProtoReflect.Descriptor instead.
func (*VolumeStatus) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{31}
}

func (x *VolumeStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeStatus) GetActiveState() ActiveState {
	if x != nil {
		return x.ActiveState
	}
	return ActiveState_ACTIVE_STATE_UNSPECIFIED
}

func (x *VolumeStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type NetworkStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ActiveState   ActiveState            `protobuf:"varint,2,opt,name=active_state,json=activeState,proto3,enum=syslet.v1.ActiveState" json:"active_state,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStatus) Reset() {
	*x = NetworkStatus{}
	mi := &file_proto_syslet_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatus) ProtoMessage() {}

func (x *NetworkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatus.ProtoReflect.Descriptor instead.
func (*NetworkStatus) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{32}
}

func (x *NetworkStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkStatus) GetActiveState() ActiveState {
	if x != nil {
		return x.ActiveState
	}
	return ActiveState_ACTIVE_STATE_UNSPECIFIED
}

func (x *NetworkStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnitName      string                 `protobuf:"bytes,1,opt,name=unit_name,json=unitName,proto3" json:"unit_name,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	Lines         int32                  `protobuf:"varint,3,opt,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_proto_syslet_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{33}
}

func (x *LogsRequest) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_syslet_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syslet_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_syslet_proto_rawDescGZIP(), []int{34}
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

var File_proto_syslet_proto protoreflect.FileDescriptor

const file_proto_syslet_proto_rawDesc = "" +
	"\n" +
	"\x12proto/syslet.proto\x12\tsyslet.v1\"P\n" +
	"\n" +
	"UnitOption\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"U\n" +
	"\vConfigEntry\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12,\n" +
	"\x12target_volume_path\x18\x02 \x01(\tR\x10targetVolumePath\"U\n" +
	"\vApplyResult\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\achanged\x18\x02 \x01(\bR\achanged\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xc4\x01\n" +
	"\rContainerSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\rdesired_state\x18\x02 \x01(\x0e2\x17.syslet.v1.DesiredStateR\fdesiredState\x12/\n" +
	"\aoptions\x18\x03 \x03(\v2\x15.syslet.v1.UnitOptionR\aoptions\x120\n" +
	"\aconfigs\x18\x04 \x03(\v2\x16.syslet.v1.ConfigEntryR\aconfigs\"Q\n" +
	"\n" +
	"VolumeSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\aoptions\x18\x02 \x03(\v2\x15.syslet.v1.UnitOptionR\aoptions\"R\n" +
	"\vNetworkSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\aoptions\x18\x02 \x03(\v2\x15.syslet.v1.UnitOptionR\aoptions\"H\n" +
	"\x16ApplyContainersRequest\x12.\n" +
	"\x05specs\x18\x01 \x03(\v2\x18.syslet.v1.ContainerSpecR\x05specs\"K\n" +
	"\x17ApplyContainersResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.syslet.v1.ApplyResultR\aresults\")\n" +
	"\x13GetContainerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"P\n" +
	"\x14GetContainerResponse\x128\n" +
	"\tcontainer\x18\x01 \x01(\v2\x1a.syslet.v1.ContainerStatusR\tcontainer\"\x17\n" +
	"\x15ListContainersRequest\"T\n" +
	"\x16ListContainersResponse\x12:\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x1a.syslet.v1.ContainerStatusR\n" +
	"containers\",\n" +
	"\x16DeleteContainerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"3\n" +
	"\x17DeleteContainerResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"B\n" +
	"\x13ApplyVolumesRequest\x12+\n" +
	"\x05specs\x18\x01 \x03(\v2\x15.syslet.v1.VolumeSpecR\x05specs\"H\n" +
	"\x14ApplyVolumesResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.syslet.v1.ApplyResultR\aresults\"&\n" +
	"\x10GetVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x11GetVolumeResponse\x12/\n" +
	"\x06volume\x18\x01 \x01(\v2\x17.syslet.v1.VolumeStatusR\x06volume\"\x14\n" +
	"\x12ListVolumesRequest\"H\n" +
	"\x13ListVolumesResponse\x121\n" +
	"\avolumes\x18\x01 \x03(\v2\x17.syslet.v1.VolumeStatusR\avolumes\")\n" +
	"\x13DeleteVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"0\n" +
	"\x14DeleteVolumeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"D\n" +
	"\x14ApplyNetworksRequest\x12,\n" +
	"\x05specs\x18\x01 \x03(\v2\x16.syslet.v1.NetworkSpecR\x05specs\"I\n" +
	"\x15ApplyNetworksResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.syslet.v1.ApplyResultR\aresults\"'\n" +
	"\x11GetNetworkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x12GetNetworkResponse\x122\n" +
	"\anetwork\x18\x01 \x01(\v2\x18.syslet.v1.NetworkStatusR\anetwork\"\x15\n" +
	"\x13ListNetworksRequest\"L\n" +
	"\x14ListNetworksResponse\x124\n" +
	"\bnetworks\x18\x01 \x03(\v2\x18.syslet.v1.NetworkStatusR\bnetworks\"*\n" +
	"\x14DeleteNetworkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x15DeleteNetworkResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x9d\x01\n" +
	"\x0fContainerStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\factive_state\x18\x03 \x01(\x0e2\x16.syslet.v1.ActiveStateR\vactiveState\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12!\n" +
	"\fconfig_files\x18\x05 \x03(\tR\vconfigFiles\"w\n" +
	"\fVolumeStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\factive_state\x18\x02 \x01(\x0e2\x16.syslet.v1.ActiveStateR\vactiveState\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"x\n" +
	"\rNetworkStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\factive_state\x18\x02 \x01(\x0e2\x16.syslet.v1.ActiveStateR\vactiveState\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"X\n" +
	"\vLogsRequest\x12\x1b\n" +
	"\tunit_name\x18\x01 \x01(\tR\bunitName\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x14\n" +
	"\x05lines\x18\x03 \x01(\x05R\x05lines\"^\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority*c\n" +
	"\fDesiredState\x12\x1d\n" +
	"\x19DESIRED_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DESIRED_STATE_RUNNING\x10\x01\x12\x19\n" +
	"\x15DESIRED_STATE_STOPPED\x10\x02*\xb4\x01\n" +
	"\vActiveState\x12\x1c\n" +
	"\x18ACTIVE_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACTIVE_STATE_ACTIVE\x10\x01\x12\x19\n" +
	"\x15ACTIVE_STATE_INACTIVE\x10\x02\x12\x17\n" +
	"\x13ACTIVE_STATE_FAILED\x10\x03\x12\x1b\n" +
	"\x17ACTIVE_STATE_ACTIVATING\x10\x04\x12\x1d\n" +
	"\x19ACTIVE_STATE_DEACTIVATING\x10\x052\x9e\b\n" +
	"\rSysletService\x12X\n" +
	"\x0fApplyContainers\x12!.syslet.v1.ApplyContainersRequest\x1a\".syslet.v1.ApplyContainersResponse\x12O\n" +
	"\fGetContainer\x12\x1e.syslet.v1.GetContainerRequest\x1a\x1f.syslet.v1.GetContainerResponse\x12U\n" +
	"\x0eListContainers\x12 .syslet.v1.ListContainersRequest\x1a!.syslet.v1.ListContainersResponse\x12X\n" +
	"\x0fDeleteContainer\x12!.syslet.v1.DeleteContainerRequest\x1a\".syslet.v1.DeleteContainerResponse\x12O\n" +
	"\fApplyVolumes\x12\x1e.syslet.v1.ApplyVolumesRequest\x1a\x1f.syslet.v1.ApplyVolumesResponse\x12F\n" +
	"\tGetVolume\x12\x1b.syslet.v1.GetVolumeRequest\x1a\x1c.syslet.v1.GetVolumeResponse\x12L\n" +
	"\vListVolumes\x12\x1d.syslet.v1.ListVolumesRequest\x1a\x1e.syslet.v1.ListVolumesResponse\x12O\n" +
	"\fDeleteVolume\x12\x1e.syslet.v1.DeleteVolumeRequest\x1a\x1f.syslet.v1.DeleteVolumeResponse\x12R\n" +
	"\rApplyNetworks\x12\x1f.syslet.v1.ApplyNetworksRequest\x1a .syslet.v1.ApplyNetworksResponse\x12I\n" +
	"\n" +
	"GetNetwork\x12\x1c.syslet.v1.GetNetworkRequest\x1a\x1d.syslet.v1.GetNetworkResponse\x12O\n" +
	"\fListNetworks\x12\x1e.syslet.v1.ListNetworksRequest\x1a\x1f.syslet.v1.ListNetworksResponse\x12R\n" +
	"\rDeleteNetwork\x12\x1f.syslet.v1.DeleteNetworkRequest\x1a .syslet.v1.DeleteNetworkResponse\x125\n" +
	"\x04Logs\x12\x16.syslet.v1.LogsRequest\x1a\x13.syslet.v1.LogEntry0\x01B.Z,codeberg.org/xchangeee/syslet/proto;sysletv1b\x06proto3"

var (
	file_proto_syslet_proto_rawDescOnce sync.Once
	file_proto_syslet_proto_rawDescData []byte
)

func file_proto_syslet_proto_rawDescGZIP() []byte {
	file_proto_syslet_proto_rawDescOnce.Do(func() {
		file_proto_syslet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_syslet_proto_rawDesc), len(file_proto_syslet_proto_rawDesc)))
	})
	return file_proto_syslet_proto_rawDescData
}

var file_proto_syslet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_syslet_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_syslet_proto_goTypes = []any{
	(DesiredState)(0),               // 0: syslet.v1.DesiredState
	(ActiveState)(0),                // 1: syslet.v1.ActiveState
	(*UnitOption)(nil),              // 2: syslet.v1.UnitOption
	(*ConfigEntry)(nil),             // 3: syslet.v1.ConfigEntry
	(*ApplyResult)(nil),             // 4: syslet.v1.ApplyResult
	(*ContainerSpec)(nil),           // 5: syslet.v1.ContainerSpec
	(*VolumeSpec)(nil),              // 6: syslet.v1.VolumeSpec
	(*NetworkSpec)(nil),             // 7: syslet.v1.NetworkSpec
	(*ApplyContainersRequest)(nil),  // 8: syslet.v1.ApplyContainersRequest
	(*ApplyContainersResponse)(nil), // 9: syslet.v1.ApplyContainersResponse
	(*GetContainerRequest)(nil),     // 10: syslet.v1.GetContainerRequest
	(*GetContainerResponse)(nil),    // 11: syslet.v1.GetContainerResponse
	(*ListContainersRequest)(nil),   // 12: syslet.v1.ListContainersRequest
	(*ListContainersResponse)(nil),  // 13: syslet.v1.ListContainersResponse
	(*DeleteContainerRequest)(nil),  // 14: syslet.v1.DeleteContainerRequest
	(*DeleteContainerResponse)(nil), // 15: syslet.v1.DeleteContainerResponse
	(*ApplyVolumesRequest)(nil),     // 16: syslet.v1.ApplyVolumesRequest
	(*ApplyVolumesResponse)(nil),    // 17: syslet.v1.ApplyVolumesResponse
	(*GetVolumeRequest)(nil),        // 18: syslet.v1.GetVolumeRequest
	(*GetVolumeResponse)(nil),       // 19: syslet.v1.GetVolumeResponse
	(*ListVolumesRequest)(nil),      // 20: syslet.v1.ListVolumesRequest
	(*ListVolumesResponse)(nil),     // 21: syslet.v1.ListVolumesResponse
	(*DeleteVolumeRequest)(nil),     // 22: syslet.v1.DeleteVolumeRequest
	(*DeleteVolumeResponse)(nil),    // 23: syslet.v1.DeleteVolumeResponse
	(*ApplyNetworksRequest)(nil),    // 24: syslet.v1.ApplyNetworksRequest
	(*ApplyNetworksResponse)(nil),   // 25: syslet.v1.ApplyNetworksResponse
	(*GetNetworkRequest)(nil),       // 26: syslet.v1.GetNetworkRequest
	(*GetNetworkResponse)(nil),      // 27: syslet.v1.GetNetworkResponse
	(*ListNetworksRequest)(nil),     // 28: syslet.v1.ListNetworksRequest
	(*ListNetworksResponse)(nil),    // 29: syslet.v1.ListNetworksResponse
	(*DeleteNetworkRequest)(nil),    // 30: syslet.v1.DeleteNetworkRequest
	(*DeleteNetworkResponse)(nil),   // 31: syslet.v1.DeleteNetworkResponse
	(*ContainerStatus)(nil),         // 32: syslet.v1.ContainerStatus
	(*VolumeStatus)(nil),            // 33: syslet.v1.VolumeStatus
	(*NetworkStatus)(nil),           // 34: syslet.v1.NetworkStatus
	(*LogsRequest)(nil),             // 35: syslet.v1.LogsRequest
	(*LogEntry)(nil),                // 36: syslet.v1.LogEntry
}
var file_proto_syslet_proto_depIdxs = []int32{
	0,  // 0: syslet.v1.ContainerSpec.desired_state:type_name -> syslet.v1.DesiredState
	2,  // 1: syslet.v1.ContainerSpec.options:type_name -> syslet.v1.UnitOption
	3,  // 2: syslet.v1.ContainerSpec.configs:type_name -> syslet.v1.ConfigEntry
	2,  // 3: syslet.v1.VolumeSpec.options:type_name -> syslet.v1.UnitOption
	2,  // 4: syslet.v1.NetworkSpec.options:type_name -> syslet.v1.UnitOption
	5,  // 5: syslet.v1.ApplyContainersRequest.specs:type_name -> syslet.v1.ContainerSpec
	4,  // 6: syslet.v1.ApplyContainersResponse.results:type_name -> syslet.v1.ApplyResult
	32, // 7: syslet.v1.GetContainerResponse.container:type_name -> syslet.v1.ContainerStatus
	32, // 8: syslet.v1.ListContainersResponse.containers:type_name -> syslet.v1.ContainerStatus
	6,  // 9: syslet.v1.ApplyVolumesRequest.specs:type_name -> syslet.v1.VolumeSpec
	4,  // 10: syslet.v1.ApplyVolumesResponse.results:type_name -> syslet.v1.ApplyResult
	33, // 11: syslet.v1.GetVolumeResponse.volume:type_name -> syslet.v1.VolumeStatus
	33, // 12: syslet.v1.ListVolumesResponse.volumes:type_name -> syslet.v1.VolumeStatus
	7,  // 13: syslet.v1.ApplyNetworksRequest.specs:type_name -> syslet.v1.NetworkSpec
	4,  // 14: syslet.v1.ApplyNetworksResponse.results:type_name -> syslet.v1.ApplyResult
	34, // 15: syslet.v1.GetNetworkResponse.network:type_name -> syslet.v1.NetworkStatus
	34, // 16: syslet.v1.ListNetworksResponse.networks:type_name -> syslet.v1.NetworkStatus
	1,  // 17: syslet.v1.ContainerStatus.active_state:type_name -> syslet.v1.ActiveState
	1,  // 18: syslet.v1.VolumeStatus.active_state:type_name -> syslet.v1.ActiveState
	1,  // 19: syslet.v1.NetworkStatus.active_state:type_name -> syslet.v1.ActiveState
	8,  // 20: syslet.v1.SysletService.ApplyContainers:input_type -> syslet.v1.ApplyContainersRequest
	10, // 21: syslet.v1.SysletService.GetContainer:input_type -> syslet.v1.GetContainerRequest
	12, // 22: syslet.v1.SysletService.ListContainers:input_type -> syslet.v1.ListContainersRequest
	14, // 23: syslet.v1.SysletService.DeleteContainer:input_type -> syslet.v1.DeleteContainerRequest
	16, // 24: syslet.v1.SysletService.ApplyVolumes:input_type -> syslet.v1.ApplyVolumesRequest
	18, // 25: syslet.v1.SysletService.GetVolume:input_type -> syslet.v1.GetVolumeRequest
	20, // 26: syslet.v1.SysletService.ListVolumes:input_type -> syslet.v1.ListVolumesRequest
	22, // 27: syslet.v1.SysletService.DeleteVolume:input_type -> syslet.v1.DeleteVolumeRequest
	24, // 28: syslet.v1.SysletService.ApplyNetworks:input_type -> syslet.v1.ApplyNetworksRequest
	26, // 29: syslet.v1.SysletService.GetNetwork:input_type -> syslet.v1.GetNetworkRequest
	28, // 30: syslet.v1.SysletService.ListNetworks:input_type -> syslet.v1.ListNetworksRequest
	30, // 31: syslet.v1.SysletService.DeleteNetwork:input_type -> syslet.v1.DeleteNetworkRequest
	35, // 32: syslet.v1.SysletService.Logs:input_type -> syslet.v1.LogsRequest
	9,  // 33: syslet.v1.SysletService.ApplyContainers:output_type -> syslet.v1.ApplyContainersResponse
	11, // 34: syslet.v1.SysletService.GetContainer:output_type -> syslet.v1.GetContainerResponse
	13, // 35: syslet.v1.SysletService.ListContainers:output_type -> syslet.v1.ListContainersResponse
	15, // 36: syslet.v1.SysletService.DeleteContainer:output_type -> syslet.v1.DeleteContainerResponse
	17, // 37: syslet.v1.SysletService.ApplyVolumes:output_type -> syslet.v1.ApplyVolumesResponse
	19, // 38: syslet.v1.SysletService.GetVolume:output_type -> syslet.v1.GetVolumeResponse
	21, // 39: syslet.v1.SysletService.ListVolumes:output_type -> syslet.v1.ListVolumesResponse
	23, // 40: syslet.v1.SysletService.DeleteVolume:output_type -> syslet.v1.DeleteVolumeResponse
	25, // 41: syslet.v1.SysletService.ApplyNetworks:output_type -> syslet.v1.ApplyNetworksResponse
	27, // 42: syslet.v1.SysletService.GetNetwork:output_type -> syslet.v1.GetNetworkResponse
	29, // 43: syslet.v1.SysletService.ListNetworks:output_type -> syslet.v1.ListNetworksResponse
	31, // 44: syslet.v1.SysletService.DeleteNetwork:output_type -> syslet.v1.DeleteNetworkResponse
	36, // 45: syslet.v1.SysletService.Logs:output_type -> syslet.v1.LogEntry
	33, // [33:46] is the sub-list for method output_type
	20, // [20:33] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_syslet_proto_init() }
func file_proto_syslet_proto_init() {
	if File_proto_syslet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_syslet_proto_rawDesc), len(file_proto_syslet_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_syslet_proto_goTypes,
		DependencyIndexes: file_proto_syslet_proto_depIdxs,
		EnumInfos:         file_proto_syslet_proto_enumTypes,
		MessageInfos:      file_proto_syslet_proto_msgTypes,
	}.Build()
	File_proto_syslet_proto = out.File
	file_proto_syslet_proto_goTypes = nil
	file_proto_syslet_proto_depIdxs = nil
}
