// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/syslet.proto

package sysletv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysletService_ApplyContainers_FullMethodName = "/syslet.v1.SysletService/ApplyContainers"
	SysletService_GetContainer_FullMethodName    = "/syslet.v1.SysletService/GetContainer"
	SysletService_ListContainers_FullMethodName  = "/syslet.v1.SysletService/ListContainers"
	SysletService_DeleteContainer_FullMethodName = "/syslet.v1.SysletService/DeleteContainer"
	SysletService_ApplyVolumes_FullMethodName    = "/syslet.v1.SysletService/ApplyVolumes"
	SysletService_GetVolume_FullMethodName       = "/syslet.v1.SysletService/GetVolume"
	SysletService_ListVolumes_FullMethodName     = "/syslet.v1.SysletService/ListVolumes"
	SysletService_DeleteVolume_FullMethodName    = "/syslet.v1.SysletService/DeleteVolume"
	SysletService_ApplyNetworks_FullMethodName   = "/syslet.v1.SysletService/ApplyNetworks"
	SysletService_GetNetwork_FullMethodName      = "/syslet.v1.SysletService/GetNetwork"
	SysletService_ListNetworks_FullMethodName    = "/syslet.v1.SysletService/ListNetworks"
	SysletService_DeleteNetwork_FullMethodName   = "/syslet.v1.SysletService/DeleteNetwork"
	SysletService_Logs_FullMethodName            = "/syslet.v1.SysletService/Logs"
)

// SysletServiceClient is the client API for SysletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysletServiceClient interface {
	// Container RPCs
	ApplyContainers(ctx context.Context, in *ApplyContainersRequest, opts ...grpc.CallOption) (*ApplyContainersResponse, error)
	GetContainer(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*GetContainerResponse, error)
	ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error)
	DeleteContainer(ctx context.Context, in *DeleteContainerRequest, opts ...grpc.CallOption) (*DeleteContainerResponse, error)
	// Volume RPCs
	ApplyVolumes(ctx context.Context, in *ApplyVolumesRequest, opts ...grpc.CallOption) (*ApplyVolumesResponse, error)
	GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error)
	ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error)
	DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error)
	// Network RPCs
	ApplyNetworks(ctx context.Context, in *ApplyNetworksRequest, opts ...grpc.CallOption) (*ApplyNetworksResponse, error)
	GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error)
	ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error)
	DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error)
	// Logs (container-only)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
}

type sysletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSysletServiceClient(cc grpc.ClientConnInterface) SysletServiceClient {
	return &sysletServiceClient{cc}
}

func (c *sysletServiceClient) ApplyContainers(ctx context.Context, in *ApplyContainersRequest, opts ...grpc.CallOption) (*ApplyContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyContainersResponse)
	err := c.cc.Invoke(ctx, SysletService_ApplyContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) GetContainer(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*GetContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerResponse)
	err := c.cc.Invoke(ctx, SysletService_GetContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContainersResponse)
	err := c.cc.Invoke(ctx, SysletService_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) DeleteContainer(ctx context.Context, in *DeleteContainerRequest, opts ...grpc.CallOption) (*DeleteContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContainerResponse)
	err := c.cc.Invoke(ctx, SysletService_DeleteContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) ApplyVolumes(ctx context.Context, in *ApplyVolumesRequest, opts ...grpc.CallOption) (*ApplyVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyVolumesResponse)
	err := c.cc.Invoke(ctx, SysletService_ApplyVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVolumeResponse)
	err := c.cc.Invoke(ctx, SysletService_GetVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) ListVolumes(ctx context.Context, in *ListVolumesRequest, opts ...grpc.CallOption) (*ListVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVolumesResponse)
	err := c.cc.Invoke(ctx, SysletService_ListVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVolumeResponse)
	err := c.cc.Invoke(ctx, SysletService_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) ApplyNetworks(ctx context.Context, in *ApplyNetworksRequest, opts ...grpc.CallOption) (*ApplyNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyNetworksResponse)
	err := c.cc.Invoke(ctx, SysletService_ApplyNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkResponse)
	err := c.cc.Invoke(ctx, SysletService_GetNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworksResponse)
	err := c.cc.Invoke(ctx, SysletService_ListNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) DeleteNetwork(ctx context.Context, in *DeleteNetworkRequest, opts ...grpc.CallOption) (*DeleteNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNetworkResponse)
	err := c.cc.Invoke(ctx, SysletService_DeleteNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysletServiceClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SysletService_ServiceDesc.Streams[0], SysletService_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SysletService_LogsClient = grpc.ServerStreamingClient[LogEntry]

// SysletServiceServer is the server API for SysletService service.
// All implementations must embed UnimplementedSysletServiceServer
// for forward compatibility.
type SysletServiceServer interface {
	// Container RPCs
	ApplyContainers(context.Context, *ApplyContainersRequest) (*ApplyContainersResponse, error)
	GetContainer(context.Context, *GetContainerRequest) (*GetContainerResponse, error)
	ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error)
	DeleteContainer(context.Context, *DeleteContainerRequest) (*DeleteContainerResponse, error)
	// Volume RPCs
	ApplyVolumes(context.Context, *ApplyVolumesRequest) (*ApplyVolumesResponse, error)
	GetVolume(context.Context, *GetVolumeRequest) (*GetVolumeResponse, error)
	ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error)
	DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error)
	// Network RPCs
	ApplyNetworks(context.Context, *ApplyNetworksRequest) (*ApplyNetworksResponse, error)
	GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error)
	ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error)
	DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error)
	// Logs (container-only)
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	mustEmbedUnimplementedSysletServiceServer()
}

// UnimplementedSysletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysletServiceServer struct{}

func (UnimplementedSysletServiceServer) ApplyContainers(context.Context, *ApplyContainersRequest) (*ApplyContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyContainers not implemented")
}
func (UnimplementedSysletServiceServer) GetContainer(context.Context, *GetContainerRequest) (*GetContainerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContainer not implemented")
}
func (UnimplementedSysletServiceServer) ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedSysletServiceServer) DeleteContainer(context.Context, *DeleteContainerRequest) (*DeleteContainerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteContainer not implemented")
}
func (UnimplementedSysletServiceServer) ApplyVolumes(context.Context, *ApplyVolumesRequest) (*ApplyVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyVolumes not implemented")
}
func (UnimplementedSysletServiceServer) GetVolume(context.Context, *GetVolumeRequest) (*GetVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVolume not implemented")
}
func (UnimplementedSysletServiceServer) ListVolumes(context.Context, *ListVolumesRequest) (*ListVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVolumes not implemented")
}
func (UnimplementedSysletServiceServer) DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedSysletServiceServer) ApplyNetworks(context.Context, *ApplyNetworksRequest) (*ApplyNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyNetworks not implemented")
}
func (UnimplementedSysletServiceServer) GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetwork not implemented")
}
func (UnimplementedSysletServiceServer) ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworks not implemented")
}
func (UnimplementedSysletServiceServer) DeleteNetwork(context.Context, *DeleteNetworkRequest) (*DeleteNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNetwork not implemented")
}
func (UnimplementedSysletServiceServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedSysletServiceServer) mustEmbedUnimplementedSysletServiceServer() {}
func (UnimplementedSysletServiceServer) testEmbeddedByValue()                       {}

// UnsafeSysletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysletServiceServer will
// result in compilation errors.
type UnsafeSysletServiceServer interface {
	mustEmbedUnimplementedSysletServiceServer()
}

func RegisterSysletServiceServer(s grpc.ServiceRegistrar, srv SysletServiceServer) {
	// If the following call panics, it indicates UnimplementedSysletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysletService_ServiceDesc, srv)
}

func _SysletService_ApplyContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).ApplyContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_ApplyContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).ApplyContainers(ctx, req.(*ApplyContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_GetContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).GetContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_GetContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).GetContainer(ctx, req.(*GetContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).ListContainers(ctx, req.(*ListContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_DeleteContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).DeleteContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_DeleteContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).DeleteContainer(ctx, req.(*DeleteContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_ApplyVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).ApplyVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_ApplyVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).ApplyVolumes(ctx, req.(*ApplyVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_GetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).GetVolume(ctx, req.(*GetVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).ListVolumes(ctx, req.(*ListVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).DeleteVolume(ctx, req.(*DeleteVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_ApplyNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).ApplyNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_ApplyNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).ApplyNetworks(ctx, req.(*ApplyNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_GetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).GetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_GetNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).GetNetwork(ctx, req.(*GetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_ListNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).ListNetworks(ctx, req.(*ListNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_DeleteNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysletServiceServer).DeleteNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysletService_DeleteNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysletServiceServer).DeleteNetwork(ctx, req.(*DeleteNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysletService_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SysletServiceServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SysletService_LogsServer = grpc.ServerStreamingServer[LogEntry]

// SysletService_ServiceDesc is the grpc.ServiceDesc for SysletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syslet.v1.SysletService",
	HandlerType: (*SysletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyContainers",
			Handler:    _SysletService_ApplyContainers_Handler,
		},
		{
			MethodName: "GetContainer",
			Handler:    _SysletService_GetContainer_Handler,
		},
		{
			MethodName: "ListContainers",
			Handler:    _SysletService_ListContainers_Handler,
		},
		{
			MethodName: "DeleteContainer",
			Handler:    _SysletService_DeleteContainer_Handler,
		},
		{
			MethodName: "ApplyVolumes",
			Handler:    _SysletService_ApplyVolumes_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _SysletService_GetVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _SysletService_ListVolumes_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _SysletService_DeleteVolume_Handler,
		},
		{
			MethodName: "ApplyNetworks",
			Handler:    _SysletService_ApplyNetworks_Handler,
		},
		{
			MethodName: "GetNetwork",
			Handler:    _SysletService_GetNetwork_Handler,
		},
		{
			MethodName: "ListNetworks",
			Handler:    _SysletService_ListNetworks_Handler,
		},
		{
			MethodName: "DeleteNetwork",
			Handler:    _SysletService_DeleteNetwork_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _SysletService_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/syslet.proto",
}
